### ISSUE TITLE
关于阅读数和http引入的问题

### ISSUE THREAD

**Issue by yuzmb** [winnerweb/hexo-theme-smackdown#1]
阅读数怎么配置出来呀？还有，github.io是基于https访问的，但是index.html文件有htpp的引入，这样打开博客默认没有动画和头像，要浏览器加载不安全脚本才有。但是我把http的引入(比如jq的)改成本地的，写完文章同步到github后，index文件又会自己修改的，变回原样的了，能解决吗？

**Comment by smackgg** [comment]
sorry， 我刚看到你的问题。
第一个问题，关于阅读数如何配置的问题，我一直没有时间写readme，等我明天有时间重新写一下详细教程。
第二个https的问题，看一下这里https://help.github.com/articles/securing-your-github-pages-site-with-https/
Enforce HTTPS不要打勾，否则就是会强制https。

**Comment by yuzmb** [comment]
ok

**Comment by yuzmb** [comment]
https://github.com/blog/2186-https-for-github-pages  现在已经强制要用https了 在设置里 那个勾默认有的 不了取消

**Comment by smackgg** [comment]
@yuzmb 为什么我的可以？明天我再看一下吧

**Comment by smackgg** [comment]
@yuzmb 主题已经更新，解决https下js加载问题。头像自己换成https的图片或者本地图片。
关于阅读数的配置参考[这篇文章](http://blog.smackdown.gebilaowu.cn/2016/10/31/hexo%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E9%98%85%E8%AF%BB%E6%95%B0/)
