### ISSUE TITLE
开启了多说但是没有生效

### ISSUE THREAD

**Issue by AlicePrincess** [winnerweb/hexo-theme-smackdown#3]
地址:  alice.xiaomo.info
请教一下是什么原因

**Comment by smackgg** [comment]
因为你的多说的js文件没有加载成功，你现在是https，但是多说的是http
![image](https://cloud.githubusercontent.com/assets/13075469/23331479/df1ddcb4-fba1-11e6-8078-b4dd81958468.png)

**Comment by smackgg** [comment]
额。。我看错了。。
你等一天再看看吧，你现在的配置没什么问题。是多说自己挂掉了。
![image](https://cloud.githubusercontent.com/assets/13075469/23331492/15d244b6-fba2-11e6-969b-be7d7e02772c.png)
![image](https://cloud.githubusercontent.com/assets/13075469/23331493/1c6a32ac-fba2-11e6-98eb-0706ea0b1cbb.png)

我自己的博客多说也不好使了。

**Comment by smackgg** [comment]
@AlicePrincess 现在我的好使了，你的还是不好使，一直报服务器异常，你联系一下多说的客服吧。

![image](https://cloud.githubusercontent.com/assets/13075469/23331568/9020a32e-fba3-11e6-80ab-fecc19dcd05b.png)
